server:
  port: 10010
spring:
  application:
    name: ly-registry
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5

zuul:
  prefix: /api
  routes:
    item-service: /item/** #路由到商品为服务
    search-service: /search/**
  ignored-services:
    -upload-service # 忽略upload-service服务


