server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.1.177
    username: /leyou
    password: 123456
    virtual-host: /leyou

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka

leyou:
  sms:
    accessKeyId: #*** # 你自己的accessKeyId
    accessKeySecret: #*** # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: #*** # 模板名称

