server:
  port: 8081
spring:
  application:
    name: item-service

  datasource:
    url: jdbc:mysql:///leyou
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.leyou.item.pojo